# Generated by Django 6.0.1 on 2026-01-14 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, verbose_name='Địa chỉ')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Ảnh đại diện')),
                ('role', models.CharField(choices=[('user', 'Người dùng'), ('admin', 'Quản trị viên')], default='user', max_length=10, verbose_name='Vai trò')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Nhân viên')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email đã xác thực')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tham gia')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Đăng nhập cuối')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
