# Generated by Django 6.0.1 on 2026-01-14 00:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Mã đơn hàng')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Tạm tính')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=15000, max_digits=10, verbose_name='Phí vận chuyển')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giảm giá')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Tổng tiền')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('returned', 'Hoàn trả')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo'), ('vnpay', 'VNPay')], default='cod', max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày xác nhận')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giao')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày hủy')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Lý do hủy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'db_table': 'orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('product_image', models.CharField(blank=True, max_length=255, verbose_name='Hình ảnh')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Thành tiền')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thêm')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Sản phẩm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
                'db_table': 'cart_items',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_user_id_17dbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
    ]
