# Generated by Django 6.0.1 on 2026-01-14 00:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá khuyến mãi')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng tồn kho')),
                ('unit', models.CharField(default='gói', max_length=20, verbose_name='Đơn vị')),
                ('weight_grams', models.IntegerField(blank=True, null=True, verbose_name='Khối lượng (g)')),
                ('sold_count', models.IntegerField(default=0, verbose_name='Đã bán')),
                ('view_count', models.IntegerField(default=0, verbose_name='Lượt xem')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Đánh giá trung bình')),
                ('review_count', models.IntegerField(default=0, verbose_name='Số đánh giá')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Hình ảnh')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ảnh chính')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
                'db_table': 'product_images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
